/**
 * Generated by `pnpm kysely-codegen` for reference only.
 * We use slightly better custom branded types based on this output.
 */

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CalendarArchive {
  created_at: Generated<string>;
  data: string | null;
  end_datetime_utc: number;
  event_id: Generated<number | null>;
  start_datetime_utc: number;
  type: string;
  updated_at: Generated<string>;
  version: Generated<number>;
}

export interface Sessions {
  created_at: Generated<string | null>;
  expires_at: string | null;
  session_id: string;
  username: string;
}

export interface DB {
  calendar_archive: CalendarArchive;
  sessions: Sessions;
}
